/**
 * Claude model definitions for Vertex AI
 * Pricing: https://cloud.google.com/vertex-ai/generative-ai/pricing#partner-models
 * All prices per 1M tokens (as of Feb 2025)
 * Cache write prices shown are for 5-minute TTL
 */

import type { VertexModelConfig } from "../types.js";

export const CLAUDE_MODELS: VertexModelConfig[] = [
  // Claude 4.6 series - latest, supports global endpoint
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    apiId: "claude-opus-4-6",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 32000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 5.00,
      output: 25.00,
      cacheRead: 0.50,
      cacheWrite: 6.25,
    },
    region: "global",
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    apiId: "claude-sonnet-4-6",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 64000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 3.00,
      output: 15.00,
      cacheRead: 0.30,
      cacheWrite: 3.75,
    },
    region: "global",
  },
  // Claude 4.5 series - supports global endpoint
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5",
    apiId: "claude-opus-4-5@20251101",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 32000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 5.00,
      output: 25.00,
      cacheRead: 0.50,
      cacheWrite: 6.25,
    },
    region: "global",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    apiId: "claude-sonnet-4-5@20250929",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 64000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 3.00,
      output: 15.00,
      cacheRead: 0.30,
      cacheWrite: 3.75,
    },
    region: "global",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    apiId: "claude-haiku-4-5@20251001",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 64000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 1.00,
      output: 5.00,
      cacheRead: 0.10,
      cacheWrite: 1.25,
    },
    region: "global",
  },
  // Claude 4.1 series - regional pricing
  {
    id: "claude-opus-4-1",
    name: "Claude Opus 4.1",
    apiId: "claude-opus-4-1@20250805",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 32000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 15.00,
      output: 75.00,
      cacheRead: 1.50,
      cacheWrite: 18.75,
    },
    region: "us-east5",
  },
  // Claude 4.0 series - regional pricing
  {
    id: "claude-opus-4",
    name: "Claude Opus 4",
    apiId: "claude-opus-4@20250514",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 32000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 15.00,
      output: 75.00,
      cacheRead: 1.50,
      cacheWrite: 18.75,
    },
    region: "us-east5",
  },
  {
    id: "claude-sonnet-4",
    name: "Claude Sonnet 4",
    apiId: "claude-sonnet-4@20250514",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 64000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 3.00,
      output: 15.00,
      cacheRead: 0.30,
      cacheWrite: 3.75,
    },
    region: "us-east5",
  },
  // Claude 3.7 series - regional pricing
  {
    id: "claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet",
    apiId: "claude-3-7-sonnet@20250219",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 64000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 3.0,
      output: 15.0,
      cacheRead: 0.3,
      cacheWrite: 3.75,
    },
    region: "us-east5",
  },
  // Claude 3.5 series - regional pricing
  {
    id: "claude-3-5-sonnet-v2",
    name: "Claude 3.5 Sonnet v2",
    apiId: "claude-3-5-sonnet-v2@20241022",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 8192,
    input: ["text", "image"],
    reasoning: false,
    tools: true,
    cost: {
      input: 3.0,
      output: 15.0,
      cacheRead: 0.3,
      cacheWrite: 3.75,
    },
    region: "us-east5",
  },
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    apiId: "claude-3-5-sonnet@20240620",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 8192,
    input: ["text", "image"],
    reasoning: false,
    tools: true,
    cost: {
      input: 3.0,
      output: 15.0,
      cacheRead: 0.3,
      cacheWrite: 3.75,
    },
    region: "us-east5",
  },
  // Claude 3 Haiku - regional pricing
  {
    id: "claude-3-haiku",
    name: "Claude 3 Haiku",
    apiId: "claude-3-haiku@20240307",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 4096,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.25,
      output: 1.25,
      cacheRead: 0.03,
      cacheWrite: 0.3,
    },
    region: "us-east5",
  },
];
