/**
 * Gemini model definitions for Vertex AI
 * Pricing: https://cloud.google.com/vertex-ai/generative-ai/pricing#gemini-models
 * All prices per 1M tokens (Standard tier pricing, as of Feb 2026)
 */

import type { VertexModelConfig } from "../types.js";

export const GEMINI_MODELS: VertexModelConfig[] = [
  {
    id: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro",
    apiId: "gemini-3.1-pro-preview",
    publisher: "google",
    endpointType: "gemini",
    contextWindow: 1000000,
    maxTokens: 64000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 2.00,
      output: 12.00,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "gemini-3-pro",
    name: "Gemini 3 Pro",
    apiId: "gemini-3-pro-preview",
    publisher: "google",
    endpointType: "gemini",
    contextWindow: 2000000,
    maxTokens: 8192,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 1.25,
      output: 10.00,
      cacheRead: 0.125,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "gemini-3-flash",
    name: "Gemini 3 Flash",
    apiId: "gemini-3-flash-preview",
    publisher: "google",
    endpointType: "gemini",
    contextWindow: 1000000,
    maxTokens: 8192,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.15,
      output: 0.60,
      cacheRead: 0.0375,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    apiId: "gemini-2.5-pro",
    publisher: "google",
    endpointType: "gemini",
    contextWindow: 1000000,
    maxTokens: 64000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 1.25,
      output: 10.00,
      cacheRead: 0.125,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    apiId: "gemini-2.5-flash",
    publisher: "google",
    endpointType: "gemini",
    contextWindow: 1000000,
    maxTokens: 64000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.30,
      output: 2.50,
      cacheRead: 0.030,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    apiId: "gemini-2.5-flash-lite",
    publisher: "google",
    endpointType: "gemini",
    contextWindow: 1000000,
    maxTokens: 64000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.10,
      output: 0.40,
      cacheRead: 0.010,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    apiId: "gemini-2.0-flash",
    publisher: "google",
    endpointType: "gemini",
    contextWindow: 1000000,
    maxTokens: 8192,
    input: ["text", "image"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.15,
      output: 0.60,
      cacheRead: 0.025,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash Lite",
    apiId: "gemini-2.0-flash-lite",
    publisher: "google",
    endpointType: "gemini",
    contextWindow: 1000000,
    maxTokens: 8192,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.075,
      output: 0.30,
      cacheRead: 0.01875,
      cacheWrite: 0,
    },
    region: "global",
  },
];
