/**
 * MaaS (Model-as-a-Service) open model definitions for Vertex AI
 * Pricing: https://cloud.google.com/vertex-ai/generative-ai/pricing#open-models
 * All prices per 1M tokens (as of Feb 2025)
 */

import type { VertexModelConfig } from "../types.js";

export const MAAS_MODELS: VertexModelConfig[] = [
  // Llama models (Meta)
  {
    id: "llama-4-maverick",
    name: "Llama 4 Maverick",
    apiId: "meta/llama-4-maverick-17b-128e-instruct-maas",
    publisher: "meta",
    endpointType: "maas",
    contextWindow: 524288,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.35,
      output: 1.15,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "llama-4-scout",
    name: "Llama 4 Scout",
    apiId: "meta/llama-4-scout-17b-16e-instruct-maas",
    publisher: "meta",
    endpointType: "maas",
    contextWindow: 1310720,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.25,
      output: 0.70,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "llama-3.3-70b",
    name: "Llama 3.3 70B",
    apiId: "meta/llama-3.3-70b-instruct-maas",
    publisher: "meta",
    endpointType: "maas",
    contextWindow: 128000,
    maxTokens: 8192,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.72,
      output: 0.72,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },

  // Mistral models
  {
    id: "mistral-medium-3",
    name: "Mistral Medium 3",
    apiId: "mistralai/mistral-medium-3",
    publisher: "mistralai",
    endpointType: "maas",
    contextWindow: 128000,
    maxTokens: 32000,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.40,
      output: 2.00,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "mistral-small-3.1",
    name: "Mistral Small 3.1",
    apiId: "mistralai/mistral-small-2503",
    publisher: "mistralai",
    endpointType: "maas",
    contextWindow: 128000,
    maxTokens: 32000,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.10,
      output: 0.30,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "mistral-ocr",
    name: "Mistral OCR",
    apiId: "mistralai/mistral-ocr-2505",
    publisher: "mistralai",
    endpointType: "maas",
    contextWindow: 128000,
    maxTokens: 32000,
    input: ["text", "image"],
    reasoning: false,
    tools: false,
    cost: {
      input: 0.50,  // Per page: $0.0005/page, shown as approx per 1K pages
      output: 0.50,  // Per page pricing
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "codestral-2",
    name: "Codestral 2",
    apiId: "mistralai/codestral-2",
    publisher: "mistralai",
    endpointType: "maas",
    contextWindow: 256000,
    maxTokens: 32000,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.30,
      output: 0.90,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },

  // DeepSeek models
  {
    id: "deepseek-v3.2",
    name: "DeepSeek V3.2",
    apiId: "deepseek-ai/deepseek-v3.2-maas",
    publisher: "deepseek-ai",
    endpointType: "maas",
    contextWindow: 163840,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.56,
      output: 1.68,
      cacheRead: 0.056,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "deepseek-v3.1",
    name: "DeepSeek V3.1",
    apiId: "deepseek-ai/deepseek-v3.1-maas",
    publisher: "deepseek-ai",
    endpointType: "maas",
    contextWindow: 163840,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.60,
      output: 1.70,
      cacheRead: 0.06,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    apiId: "deepseek-ai/deepseek-r1-0528-maas",
    publisher: "deepseek-ai",
    endpointType: "maas",
    contextWindow: 163840,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 1.35,
      output: 5.40,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },

  // AI21 Labs models
  {
    id: "jamba-1.5-large",
    name: "Jamba 1.5 Large",
    apiId: "ai21/jamba-1.5-large",
    publisher: "ai21",
    endpointType: "maas",
    contextWindow: 256000,
    maxTokens: 256000,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 2.00,
      output: 8.00,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "jamba-1.5-mini",
    name: "Jamba 1.5 Mini",
    apiId: "ai21/jamba-1.5-mini",
    publisher: "ai21",
    endpointType: "maas",
    contextWindow: 256000,
    maxTokens: 256000,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.20,
      output: 0.40,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },

  // OpenAI models (gpt-oss)
  {
    id: "gpt-oss-120b",
    name: "GPT-OSS 120B",
    apiId: "openai/gpt-oss-120b-maas",
    publisher: "openai",
    endpointType: "maas",
    contextWindow: 131072,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.09,
      output: 0.36,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "gpt-oss-20b",
    name: "GPT-OSS 20B",
    apiId: "openai/gpt-oss-20b-maas",
    publisher: "openai",
    endpointType: "maas",
    contextWindow: 131072,
    maxTokens: 32000,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.07,
      output: 0.25,
      cacheRead: 0.007,
      cacheWrite: 0,
    },
    region: "global",
  },

  // DeepSeek OCR
  {
    id: "deepseek-ocr",
    name: "DeepSeek OCR",
    apiId: "deepseek-ai/deepseek-ocr-maas",
    publisher: "deepseek-ai",
    endpointType: "maas",
    contextWindow: 163840,
    maxTokens: 32000,
    input: ["text", "image"],
    reasoning: false,
    tools: false,
    cost: {
      input: 0.30,  // Per page: $0.0003/page
      output: 1.20,  // Per page pricing
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },

  // Qwen models
  {
    id: "qwen3-235b",
    name: "Qwen 3 235B",
    apiId: "qwen/qwen3-235b-a22b-instruct-2507-maas",
    publisher: "qwen",
    endpointType: "maas",
    contextWindow: 262144,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.22,
      output: 0.88,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "qwen3-next-instruct",
    name: "Qwen 3 Next Instruct",
    apiId: "qwen/qwen3-next-instruct-80b-maas",
    publisher: "qwen",
    endpointType: "maas",
    contextWindow: 262144,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.15,
      output: 1.20,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "qwen3-next-thinking",
    name: "Qwen 3 Next Thinking",
    apiId: "qwen/qwen3-next-thinking-80b-maas",
    publisher: "qwen",
    endpointType: "maas",
    contextWindow: 262144,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.15,
      output: 1.20,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "qwen3-coder",
    name: "Qwen 3 Coder",
    apiId: "qwen/qwen3-coder-480b-a35b-instruct-maas",
    publisher: "qwen",
    endpointType: "maas",
    contextWindow: 262144,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.22,
      output: 1.80,
      cacheRead: 0.022,
      cacheWrite: 0,
    },
    region: "global",
  },

  // Other models
  {
    id: "kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    apiId: "moonshotai/kimi-k2-thinking-maas",
    publisher: "moonshotai",
    endpointType: "maas",
    contextWindow: 262144,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.60,
      output: 2.50,
      cacheRead: 0.06,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "minimax-m2",
    name: "MiniMax M2",
    apiId: "minimaxai/minimax-m2-maas",
    publisher: "minimaxai",
    endpointType: "maas",
    contextWindow: 196608,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.30,
      output: 1.20,
      cacheRead: 0.03,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "glm-5",
    name: "GLM 5",
    apiId: "zai-org/glm-5-maas",
    publisher: "zai-org",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 1.00,
      output: 3.20,
      cacheRead: 0.10,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "glm-4.7",
    name: "GLM 4.7",
    apiId: "zai-org/glm-4.7-maas",
    publisher: "zai-org",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.60,
      output: 2.20,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
];
