/**
 * Owns the input + output sides of pi-subagents' frontmatter format.
 *
 * On the OUTPUT side, this module is the only place in the extension that
 * decides how generated agent files are assembled: which scalars get
 * quote-flipped, which strings get HTML-comment-escaped, and what the
 * deterministic field order looks like. convertAgent does the field
 * mapping but delegates the final byte assembly here.
 *
 * On the INPUT side, parseFrontmatter mirrors pi-subagents' own line-based
 * key:value parser so we can read source agents the same way pi-subagents
 * will read what we write back. The parser is deliberately naive (no nested
 * YAML, no list-of-dash arrays) -- pi-subagents is what we round-trip
 * through, not real YAML.
 */

/**
 * Marker substring written into the provenance HTML comment of every
 * generated agent file. Used by safety checks before overwriting or
 * deleting on disk: a target file without this marker is treated as
 * foreign and left alone.
 */
export const GENERATED_AGENT_MARKER = "generated by pi-claude-marketplace";

/**
 * Emit a free-text scalar in pi-subagents' frontmatter form.
 *
 * pi-subagents' parser is line-based key:value and naively strips a single
 * surrounding pair of matching quotes (`"..."` or `'...'`). If the source
 * description happens to start AND end with the same quote char, those quotes
 * would be stripped and the round-trip would lose them; and any embedded
 * newline (theoretically impossible for our line-based source parser, but
 * cheap to guard) would be misread as a key on the next line. We normalize
 * newlines to spaces and wrap in the opposing quote char only when needed.
 */
export function emitYamlScalar(value: string): string {
  const oneLine = value.replace(/\r?\n/g, " ");
  if (oneLine.startsWith('"') && oneLine.endsWith('"')) {
    return `'${oneLine}'`;
  }

  if (oneLine.startsWith("'") && oneLine.endsWith("'")) {
    return `"${oneLine}"`;
  }

  return oneLine;
}

/**
 * Sanitize a provenance comment field so a literal `-->` cannot terminate
 * the surrounding HTML comment early. The provenance block is purely
 * informational; safe to mangle the rare token.
 */
export function sanitizeProvenance(value: string): string {
  return value.replace(/-->/g, "--&gt;");
}

export interface ParsedFrontmatter {
  frontmatter: Record<string, string>;
  body: string;
}

/**
 * Parse simple `key: value` frontmatter delimited by `---` lines.
 * No nested YAML, no list-of-dash arrays. Comma-separated lists stay raw.
 */
export function parseFrontmatter(text: string): ParsedFrontmatter {
  // Frontmatter must start with `---` on its own line at the very top.
  // Accept `---\n` or `---\r\n` and also a bare `---` followed by EOF.
  const startMatch = /^---\r?\n/.exec(text);
  if (startMatch === null) {
    return { frontmatter: {}, body: normalizeBody(text) };
  }

  const afterOpen = text.slice(startMatch[0].length);
  // Find the closing `---` on its own line.
  const closeMatch = /\n---\r?\n?/.exec(afterOpen);
  if (closeMatch === null) {
    // No closing delimiter -- treat whole file as body.
    return { frontmatter: {}, body: normalizeBody(text) };
  }

  const fmText = afterOpen.slice(0, closeMatch.index);
  const body = afterOpen.slice(closeMatch.index + closeMatch[0].length);

  const frontmatter: Record<string, string> = {};
  for (const rawLine of fmText.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (line === "") {
      continue;
    }

    const colon = line.indexOf(":");
    if (colon === -1) {
      continue;
    }

    const key = line.slice(0, colon).trim();
    const value = line.slice(colon + 1).trim();
    if (key === "") {
      continue;
    }

    frontmatter[key] = value;
  }

  return { frontmatter, body: normalizeBody(body) };
}

/**
 * Normalize the body to begin with at most a single leading newline so the
 * generated file's blank-line-before-body is deterministic.
 */
export function normalizeBody(body: string): string {
  return body.replace(/^\r?\n+/, "\n");
}

/**
 * Structured frontmatter fields for a generated agent. Identifiers
 * (name, model, tools, thinking, skills) are drawn from validated enums or
 * assertSafeName-checked tokens; only `description` is free text and goes
 * through emitYamlScalar.
 */
export interface GeneratedFrontmatterFields {
  name: string;
  description: string;
  model?: string;
  tools: readonly string[];
  thinking?: string;
  skills: readonly string[];
}

/**
 * Provenance fields rendered into the HTML comment block. All free-text
 * fields are sanitized so a literal `-->` cannot terminate the comment
 * early.
 */
export interface GeneratedProvenanceFields {
  pluginName: string;
  sourceName: string;
  sourcePath: string;
  originalModel?: string;
  droppedFields: readonly string[];
  droppedTools: readonly string[];
  warnings: readonly string[];
}

/**
 * Assemble the generated agent file.
 *
 * The frontmatter MUST be the first thing in the file: pi-subagents'
 * parser only honors frontmatter when the file starts with `---`. The
 * provenance comment goes into the body so it remains human-visible (and
 * the GENERATED_AGENT_MARKER substring is still in the file for safety
 * checks before overwrite/delete).
 *
 *   <generated frontmatter>\n   (already ends with "---\n")
 *   \n
 *   <provenance comment>\n
 *   <body>
 */
export function emitGeneratedAgentFile(input: {
  frontmatter: GeneratedFrontmatterFields;
  provenance: GeneratedProvenanceFields;
  body: string;
}): string {
  const { frontmatter, provenance, body } = input;

  // Frontmatter block in deterministic order. systemPromptMode /
  // inheritProjectContext / inheritSkills are extension-side defaults and
  // intentionally hardcoded -- they describe how this bridge interacts with
  // pi-subagents and are not derived from the source agent.
  const lines: string[] = [];
  lines.push(`name: ${frontmatter.name}`);
  lines.push(`description: ${emitYamlScalar(frontmatter.description)}`);
  if (frontmatter.model !== undefined) {
    lines.push(`model: ${frontmatter.model}`);
  }

  lines.push(`tools: ${frontmatter.tools.join(",")}`);
  if (frontmatter.thinking !== undefined) {
    lines.push(`thinking: ${frontmatter.thinking}`);
  }

  if (frontmatter.skills.length > 0) {
    lines.push(`skills: ${frontmatter.skills.join(",")}`);
  }

  lines.push("systemPromptMode: replace");
  lines.push("inheritProjectContext: true");
  lines.push("inheritSkills: false");
  const generatedFrontmatter = "---\n" + lines.join("\n") + "\n---\n";

  // Provenance HTML comment. Free-text fields are sanitized so a literal
  // `-->` can't terminate the surrounding HTML comment early.
  const provenanceLines: string[] = [];
  provenanceLines.push("<!--");
  provenanceLines.push(GENERATED_AGENT_MARKER);
  provenanceLines.push(`plugin: ${provenance.pluginName}`);
  provenanceLines.push(`sourceAgent: ${provenance.sourceName}`);
  provenanceLines.push(`sourcePath: ${sanitizeProvenance(provenance.sourcePath)}`);
  if (provenance.originalModel !== undefined) {
    provenanceLines.push(`originalModel: ${sanitizeProvenance(provenance.originalModel)}`);
  }

  provenanceLines.push(
    `droppedFields: ${provenance.droppedFields.length > 0 ? sanitizeProvenance(provenance.droppedFields.join(", ")) : "(none)"}`,
  );
  provenanceLines.push(
    `droppedTools: ${provenance.droppedTools.length > 0 ? sanitizeProvenance(provenance.droppedTools.join(", ")) : "(none)"}`,
  );
  provenanceLines.push(
    `warnings: ${provenance.warnings.length > 0 ? sanitizeProvenance(provenance.warnings.join(", ")) : "(none)"}`,
  );
  provenanceLines.push("-->");
  const provenanceComment = provenanceLines.join("\n") + "\n";

  // Body: ensure exactly one leading blank line and a trailing newline so
  // the generated file has deterministic separators around the comment.
  const bodyWithLeadingBlank = body.startsWith("\n") ? body : "\n" + body;
  const bodyFinal = bodyWithLeadingBlank.endsWith("\n")
    ? bodyWithLeadingBlank
    : bodyWithLeadingBlank + "\n";

  return generatedFrontmatter + "\n" + provenanceComment + bodyFinal;
}
