import assert from "node:assert/strict";
import { copyFile, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import {
  GENERATED_AGENT_MARKER,
  GENERATED_AGENT_PREFIX,
  isOwnedAgentFile,
} from "../../../extensions/pi-claude-marketplace/bridges/agents/marker.ts";

// AG-5 two-part marker check + user-contract constants.
//
// Test layout: each case uses a fresh tmpdir under os.tmpdir() so we can
// craft files with controlled basenames + bodies without depending on
// shared state.

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FOREIGN_FIXTURES = path.resolve(HERE, "../_fixtures/foreign-agents");

async function makeTmpDir(): Promise<{ dir: string; cleanup: () => Promise<void> }> {
  const dir = await mkdtemp(path.join(tmpdir(), "pi-cm-marker-test-"));
  return {
    dir,
    cleanup: async (): Promise<void> => {
      await rm(dir, { recursive: true, force: true });
    },
  };
}

test("AG-5 isOwnedAgentFile returns ok:true for missing target (ENOENT)", async () => {
  const { dir, cleanup } = await makeTmpDir();
  try {
    const result = await isOwnedAgentFile(path.join(dir, "pi-claude-marketplace-missing.md"));
    assert.deepEqual(result, { ok: true });
  } finally {
    await cleanup();
  }
});

test("AG-5 isOwnedAgentFile returns ok:false when basename does not start with pi-claude-marketplace-", async () => {
  // Use the fixture file directly; its basename "no-marker.md" lacks the prefix.
  const result = await isOwnedAgentFile(path.join(FOREIGN_FIXTURES, "no-marker.md"));
  assert.equal(result.ok, false);
  if (result.ok) {
    throw new Error("expected ok:false");
  }

  assert.match(result.reason, /does not start with/);
  assert.match(result.reason, /pi-claude-marketplace-/);
});

test("AG-5 isOwnedAgentFile returns ok:false when body lacks marker", async () => {
  // Copy no-marker fixture to a tmpfile renamed with the pi-claude-marketplace-
  // prefix so the basename check passes but the body marker check fails.
  const { dir, cleanup } = await makeTmpDir();
  try {
    const target = path.join(dir, "pi-claude-marketplace-test.md");
    await copyFile(path.join(FOREIGN_FIXTURES, "no-marker.md"), target);
    const result = await isOwnedAgentFile(target);
    assert.equal(result.ok, false);
    if (result.ok) {
      throw new Error("expected ok:false");
    }

    assert.match(result.reason, /missing the generated marker/);
  } finally {
    await cleanup();
  }
});

test("AG-5 isOwnedAgentFile returns ok:true when basename matches AND marker present", async () => {
  // wrong-basename fixture has the marker in body; rename to pi-claude-marketplace-*.
  const { dir, cleanup } = await makeTmpDir();
  try {
    const target = path.join(dir, "pi-claude-marketplace-test.md");
    await copyFile(path.join(FOREIGN_FIXTURES, "wrong-basename.md"), target);
    const result = await isOwnedAgentFile(target);
    assert.deepEqual(result, { ok: true });
  } finally {
    await cleanup();
  }
});

test("AG-5 isOwnedAgentFile propagates non-ENOENT IO errors (EISDIR)", async () => {
  // Create a directory at a path with the proper prefix; readFile on a
  // directory throws EISDIR which must propagate (not ENOENT).
  const { dir, cleanup } = await makeTmpDir();
  try {
    const target = path.join(dir, "pi-claude-marketplace-isdir");
    const fs = await import("node:fs/promises");
    await fs.mkdir(target, { recursive: true });
    await assert.rejects(
      () => isOwnedAgentFile(target),
      (err: unknown) =>
        err instanceof Error &&
        ((err as NodeJS.ErrnoException).code === "EISDIR" ||
          (err as NodeJS.ErrnoException).code === "EACCES"),
    );
  } finally {
    await cleanup();
  }
});

test("GENERATED_AGENT_MARKER is byte-for-byte 'generated by pi-claude-marketplace'", () => {
  assert.equal(GENERATED_AGENT_MARKER, "generated by pi-claude-marketplace");
});

test("GENERATED_AGENT_PREFIX is byte-for-byte 'pi-claude-marketplace-'", () => {
  assert.equal(GENERATED_AGENT_PREFIX, "pi-claude-marketplace-");
});

test("AG-5 isOwnedAgentFile catches body-marker substring at any byte offset (legit-with-marker fixture)", async () => {
  // legit-with-marker.md fixture in foreign-agents/ has the marker in body.
  // Copy under a pi-claude-marketplace- prefix so basename check passes; marker
  // is verified to be present even though it appears mid-body.
  const { dir, cleanup } = await makeTmpDir();
  try {
    const target = path.join(dir, "pi-claude-marketplace-legit.md");
    const original = await readFile(path.join(FOREIGN_FIXTURES, "legit-with-marker.md"), "utf8");
    await writeFile(target, original);
    const result = await isOwnedAgentFile(target);
    assert.deepEqual(result, { ok: true });
  } finally {
    await cleanup();
  }
});
