// This file is auto-generated by scripts/generate-image-models.ts
// Do not edit manually - run 'npx tsx scripts/generate-image-models.ts' to update

export type ImageApi = "openai-images" | "openai-chat-image" | "google-generative-ai-image";

export interface ImageModel {
  id: string;
  name: string;
  provider: string;
  baseUrl: string;
  api: ImageApi;
  cost: number;
}

export const IMAGE_MODELS: Record<string, Record<string, ImageModel>> = {
  "google": {
    "gemini-2.0-flash-preview-image-generation": {
      id: "gemini-2.0-flash-preview-image-generation",
      name: "Gemini 2.0 Flash Image Preview",
      provider: "google",
      baseUrl: "https://generativelanguage.googleapis.com/v1beta",
      api: "google-generative-ai-image",
      cost: 0,
    },
    "imagen-3.0-generate-002": {
      id: "imagen-3.0-generate-002",
      name: "Imagen 3.0",
      provider: "google",
      baseUrl: "https://generativelanguage.googleapis.com/v1beta",
      api: "google-generative-ai-image",
      cost: 0,
    },
  },
  "openai": {
    "dall-e-2": {
      id: "dall-e-2",
      name: "DALL-E 2",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      api: "openai-images",
      cost: 0.02,
    },
    "dall-e-3": {
      id: "dall-e-3",
      name: "DALL-E 3",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      api: "openai-images",
      cost: 0.04,
    },
    "gpt-image-1": {
      id: "gpt-image-1",
      name: "GPT Image 1",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      api: "openai-images",
      cost: 0,
    },
  },
  "openrouter": {
    "black-forest-labs/flux.2-flex": {
      id: "black-forest-labs/flux.2-flex",
      name: "Black Forest Labs: FLUX.2 Flex",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "black-forest-labs/flux.2-klein-4b": {
      id: "black-forest-labs/flux.2-klein-4b",
      name: "Black Forest Labs: FLUX.2 Klein 4B",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "black-forest-labs/flux.2-max": {
      id: "black-forest-labs/flux.2-max",
      name: "Black Forest Labs: FLUX.2 Max",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "black-forest-labs/flux.2-pro": {
      id: "black-forest-labs/flux.2-pro",
      name: "Black Forest Labs: FLUX.2 Pro",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "bytedance-seed/seedream-4.5": {
      id: "bytedance-seed/seedream-4.5",
      name: "ByteDance Seed: Seedream 4.5",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "google/gemini-2.5-flash-image": {
      id: "google/gemini-2.5-flash-image",
      name: "Google: Gemini 2.5 Flash Image (Nano Banana)",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "google/gemini-2.5-flash-image-preview": {
      id: "google/gemini-2.5-flash-image-preview",
      name: "Google: Gemini 2.5 Flash Image Preview (Nano Banana)",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "google/gemini-3-pro-image-preview": {
      id: "google/gemini-3-pro-image-preview",
      name: "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "openai/gpt-5-image": {
      id: "openai/gpt-5-image",
      name: "OpenAI: GPT-5 Image",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "openai/gpt-5-image-mini": {
      id: "openai/gpt-5-image-mini",
      name: "OpenAI: GPT-5 Image Mini",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "sourceful/riverflow-v2-fast": {
      id: "sourceful/riverflow-v2-fast",
      name: "Sourceful: Riverflow V2 Fast",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "sourceful/riverflow-v2-fast-preview": {
      id: "sourceful/riverflow-v2-fast-preview",
      name: "Sourceful: Riverflow V2 Fast Preview",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "sourceful/riverflow-v2-max-preview": {
      id: "sourceful/riverflow-v2-max-preview",
      name: "Sourceful: Riverflow V2 Max Preview",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "sourceful/riverflow-v2-pro": {
      id: "sourceful/riverflow-v2-pro",
      name: "Sourceful: Riverflow V2 Pro",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
    "sourceful/riverflow-v2-standard-preview": {
      id: "sourceful/riverflow-v2-standard-preview",
      name: "Sourceful: Riverflow V2 Standard Preview",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-chat-image",
      cost: 0,
    },
  },
};
