// shared/errors-bridges.ts
//
// Typed error subclasses for Phase 3 bridge refusals. Each error type maps
// to one specific PRD failure mode; bridges throw these so callers can
// distinguish refusal categories via instanceof and so user-visible error
// messages are uniform.
//
// AgentForeignContentError EXTENDS PathContainmentError (Phase 1 D-17
// inheritance pattern). PI-14 `instanceof PathContainmentError` catches
// foreign-content refusals on the same code path as true containment
// escapes -- a foreign agent file is, in effect, an "ownership escape"
// from the extension's bookkeeping.

import path from "node:path";

import { PathContainmentError } from "./path-safety.ts";

/**
 * AG-5 refusal: target file basename does not start with
 * `pi-claude-marketplace-`, OR file body lacks the
 * `generated by pi-claude-marketplace` marker. Inherits
 * PathContainmentError so PI-14 instanceof handling propagates.
 */
export class AgentForeignContentError extends PathContainmentError {
  readonly targetPath: string;
  readonly reason: string;
  constructor(targetPath: string, reason: string) {
    // parent = directory containing target; child = target file itself.
    // Use path.dirname rather than lastIndexOf so cross-platform separators
    // (Windows backslashes) parse correctly.
    super(path.dirname(targetPath), targetPath, "agent target path");
    this.name = "AgentForeignContentError";
    this.message = `Refusing to overwrite agent file at ${targetPath}: ${reason}.`;
    this.targetPath = targetPath;
    this.reason = reason;
  }
}

/**
 * One ownership conflict surfaced by the agents-index when a generated
 * agent name in a stage operation is already owned by a different
 * (marketplace, plugin) tuple. AgentOwnershipConflictError carries an array
 * of these so callers can format multi-conflict messages.
 */
export interface AgentOwnershipConflict {
  readonly generatedName: string;
  readonly owner: { readonly marketplace: string; readonly plugin: string };
}

/**
 * AG-9 / RN-4 refusal: one or more generated agent names in the new stage
 * operation are already owned by a different (marketplace, plugin) tuple.
 * Bridge collects ALL conflicts before throwing so the user sees a single
 * loud message naming every collision rather than a stutter of refusals.
 */
export class AgentOwnershipConflictError extends Error {
  readonly conflicts: readonly AgentOwnershipConflict[];
  readonly stagingFor: { readonly marketplace: string; readonly plugin: string };
  constructor(
    stagingFor: { marketplace: string; plugin: string },
    conflicts: readonly AgentOwnershipConflict[],
  ) {
    const list = conflicts
      .map((c) => `"${c.generatedName}" already owned by ${c.owner.marketplace}/${c.owner.plugin}`)
      .join("; ");
    super(`Refusing to stage agents for ${stagingFor.marketplace}/${stagingFor.plugin}: ${list}.`);
    this.name = "AgentOwnershipConflictError";
    this.conflicts = Object.freeze([...conflicts]);
    this.stagingFor = Object.freeze({ ...stagingFor });
  }
}

/**
 * MC-4 / RN-5 refusal: a server name being staged collides with an
 * entry owned by a different scope or different plugin in the current
 * scope. Carries the colliding server name and the file path of the
 * owning entry so the user-visible message can surface both.
 */
export class McpServerCollisionError extends Error {
  readonly serverName: string;
  readonly owningPath: string;
  constructor(serverName: string, owningPath: string) {
    super(`Refusing to stage MCP server "${serverName}": already exists in ${owningPath}.`);
    this.name = "McpServerCollisionError";
    this.serverName = serverName;
    this.owningPath = owningPath;
  }
}

/**
 * Generic wrapper for prepare-time staging tmp failures (mkdtemp, partial
 * writes). Carries the underlying cause via Error.cause; downstream
 * callers may use appendLeakToError to surface cleanup leaks.
 */
export class BridgeStagingError extends Error {
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = "BridgeStagingError";
  }
}
